@echo off
:: original by koene
:: added iw4x/ported maps by gmzorz
copy sky_ft.iwi aftermath_ft.iwi
copy sky_ft.iwi art_gallery_ft.iwi
copy sky_ft.iwi chechnya_ft.iwi
copy sky_ft.iwi cobra_ft.iwi
copy sky_ft.iwi cobrapilot_ft.iwi
copy sky_ft.iwi escape_intro_ft.iwi
copy sky_ft.iwi fallujah_ft.iwi
copy sky_ft.iwi invasion_ft.iwi
copy sky_ft.iwi mp_abandon_ft.iwi
copy sky_ft.iwi mp_afghan_ft.iwi
copy sky_ft.iwi mp_canal_ft.iwi
copy sky_ft.iwi mp_crash_ft.iwi
copy sky_ft.iwi mp_fuel2_ft.iwi
copy sky_ft.iwi mp_highrise_ft.iwi
copy sky_ft.iwi mp_highrise_ft2.iwi
copy sky_ft.iwi mp_overgrown_ft.iwi
copy sky_ft.iwi mp_storm_ft.iwi
copy sky_ft.iwi mp_strike_dlc_ft.iwi
copy sky_ft.iwi mp_underpass_ft.iwi
copy sky_ft.iwi mp_rundown_ft.iwi
copy sky_ft.iwi pripyat_ft.iwi
copy sky_ft.iwi scoutsniper_ft.iwi
copy sky_ft.iwi sky_bigcity_ft.iwi
copy sky_ft.iwi sky_icbm_a_ft.iwi
copy sky_ft.iwi sky_mp_bailout_ft.iwi
copy sky_ft.iwi sky_mp_boneyard_ft.iwi
copy sky_ft.iwi sky_mp_brecourt_ft.iwi
copy sky_ft.iwi sky_mp_checkpoint_ft.iwi
copy sky_ft.iwi sky_mp_compact_ft.iwi
copy sky_ft.iwi sky_mp_highrise_ft.iwi
copy sky_ft.iwi sky_mp_nightshift_ft.iwi
copy sky_ft.iwi sky_mp_quarry_ft.iwi
copy sky_ft.iwi sky_mp_trailerpark_ft.iwi
copy sky_ft.iwi sky_mp_vacant_ft.iwi
copy sky_ft.iwi sky_so_bridge_ft.iwi
copy sky_ft.iwi sky_sp_af_chase_ft.iwi
copy sky_ft.iwi sky_sp_arcadia_ft.iwi
copy sky_ft.iwi sky_sp_boneyard_ft.iwi
copy sky_ft.iwi sky_sp_cliffhanger_ft.iwi
copy sky_ft.iwi sky_sp_gulag_ft.iwi
copy sky_ft.iwi sky_sp_roadkill_ft.iwi
copy sky_ft.iwi sky_sp_trainer_ft.iwi
copy sky_ft.iwi sp_af_caves_ft.iwi
copy sky_ft.iwi sp_airport_ft.iwi
copy sky_ft.iwi sp_contingency_ft.iwi
copy sky_ft.iwi sp_dc_burning_ft.iwi
copy sky_ft.iwi sp_dc_emp_ft.iwi
copy sky_ft.iwi sp_dc_whitehouse_ft.iwi
copy sky_ft.iwi sp_estate_ft.iwi
copy sky_ft.iwi sp_favela_escape_ft.iwi
copy sky_ft.iwi sp_favela_ft.iwi
copy sky_ft.iwi sp_hunted_ft.iwi
copy sky_ft.iwi sp_iss_ft.iwi
copy sky_ft.iwi sp_oilrig_ft.iwi
copy sky_ft.iwi codo_sky_sp_roadkill_ft.iwi
copy sky_ft.iwi skybox_mp_cosmodrome_ft.iwi
copy sky_ft.iwi sp_bog_ft.iwi
copy sky_ft.iwi skybox_mp_cosmodrome_ft.iwi
copy sky_ft.iwi sky_mp_bloc_ft.iwi
copy sky_ft.iwi skybox_sp_khe_sanh_ft.iwi
copy sky_ft.iwi codo_sp_contingency_b_ft.iwi
copy sky_ft.iwi sky_test_mp_firingrange_ft.iwi
copy sky_ft.iwi mp_crash_tropical_ft.iwi
copy sky_ft.iwi sky_test_mp_rust_ft.iwi
copy sky_ft.iwi mp_estate_tropical_ft.iwi
copy sky_ft.iwi sky_test_mp_shipment_ft.iwi
copy sky_ft.iwi mp_fav_tropical_ft.iwi
copy sky_ft.iwi chechnya_ft.iwi
copy sky_ft.iwi pripyat_ft.iwi
copy sky_ft.iwi codo_sky_sp_roadkill_ft.iwi
copy sky_ft.iwi sky_mp_cargoship_sh_ft.iwi
copy sky_ft.iwi sp_boga_ft.iwi
copy sky_ft.iwi sp_cargo_ft.iwi
copy sky_ft.iwi codo_sky_killhouse_ft.iwi
copy sky_ft.iwi ac130_ft.iwi